# Generated by Django 3.0.5 on 2022-11-18 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='assignedDrugId',
            new_name='assignedDrugsId',
        ),
    ]
